/* ════════════════════════════════════════════════════════════════════
   SITE DATA — canonical domain schema (strangler-extracted from index.html)
   Single source of truth for all domain knowledge. Published on window so the
   standalone site, the AI team, and the desktop AI can all read the same data
   without the fragile inline monolith. Loaded synchronously BEFORE the main
   inline script, which aliases it via `const SITE_SCHEMA = window.SITE_SCHEMA`.
   ════════════════════════════════════════════════════════════════════ */
window.SITE_SCHEMA = {
  version: "1.0",
  lastUpdated: "2026-06",
  domains: [
    {
      id: "ai",
      name: "AI & Computing",
      color: "#0ea5e9",
      maturity: 7,
      impact: 10,
      companies: 45,
      projects: 28,
      trl: 7,
      subdomains: [
        "Quantum-safe communication",
        "AI-driven security systems",
        "Biometric authentication technologies",
        "Foundation Models",
        "AI Agents",
        "AI Hardware/Chips",
        "Robotics AI",
        "AI Safety & Alignment",
      ],
      currentTech: [
        "Claude Sonnet 4.6 / GPT-4.1 / Gemini 2.0 Flash",
        "Multimodal AI",
        "AI Coding Agents",
        "Transformer Architecture",
      ],
      futureTech: [
        "Quantum-safe global internet (2-7yr)",
        "Autonomous AI cyber defender (3-7yr)",
        "Behavioural biometrics authentication (1-4yr)",
        "Epigenetic age reversal to cellular youth (8-16yr)",
        "Designer sensory enhancement (15-25yr)",
        "Gene-edited appearance (20-30yr)",
        "SPECULATIVE (20-100yr)",
        "CIVILISATION-SCALE (100-1000+yr)",
        "Speculative (20-100yr)",
        "Civilisation-scale (100-1000+yr)",
        "SPECULATIVE (20-100yr)",
        "CIVILISATION-SCALE (100-1000+yr)",
        "Artificial General Intelligence (5-15yr)",
        "Neuromorphic Computing (7-12yr)",
        "Quantum-AI Hybrid (15-25yr)",
      ],
      risks: [
        "Cybersecurity of critical infrastructure",
        "Digital divide in smart city access",
        "Data privacy from pervasive sensors",
        "Single points of failure in networked cities",
        "Prioritizing knowledge gaps for continuous improvement",
        "Misalignment / Loss of control",
        "Power concentration",
        "Hallucination reliability",
        "Job displacement at scale",
      ],
      dependencies: [
        "GPU compute (NVIDIA H100/B200)",
        "Training data at scale",
        "Energy infrastructure",
      ],
      successors: ["AGI", "ASI", "Brain-computer interfaces"],
    },

    {
      id: "cur",
      name: "Current Technology",
      color: "#22c55e",
      maturity: 9,
      impact: 8,
      companies: 32,
      projects: 20,
      trl: 8,
      subdomains: [
        "Quantum Computing",
        "Blockchain & Web3",
        "5G / 6G",
        "IoT & Edge",
        "Autonomous Vehicles",
      ],
      currentTech: [
        "Quantum computers (NISQ era — 1000+ qubits)",
        "Smart contracts / DeFi, precision fermentation at city scale, and AlphaFold's advancements in protein structure prediction",
        "Autonomous Drone Logistics Networks",
        "Full SAE Level 5 self-driving",
      ],
      futureTech: [
        "Fault-tolerant quantum computing (8-15yr)",
        "6G global rollout (5-8yr)",
        "Full SAE Level 5 (5-10yr)",
      ],
      risks: [
        "Quantum error rates limit scale",
        "Blockchain energy use",
        "Cybersecurity of connected vehicles",
      ],
      dependencies: [
        "Semiconductor supply chain",
        "Fiber/wireless infrastructure",
        "Global standardisation",
      ],
      successors: [
        "Quantum internet",
        "Autonomous logistics networks",
        "Molecular computing",
      ],
    },

    {
      id: "fut",
      name: "Future Technology",
      color: "#a855f7",
      maturity: 2,
      impact: 10,
      companies: 20,
      projects: 15,
      trl: 2,
      subdomains: [
        "Molecular Machines",
        "Quantum Teleportation",
        "Post-Silicon Computing",
        "Consciousness Tech",
        "Programmable Matter",
      ],
      currentTech: [
        "Proof-of-concept molecular motors",
        "Qubit teleportation (lab scale)",
        "Photonic computing (IBM, Intel)",
      ],
      futureTech: [
        "Nano-assemblers (20-40yr)",
        "Macroscopic teleportation (50yr+)",
        "Mind uploading (30-50yr)",
        "Room-temp superconductors",
      ],
      risks: [
        "Existential risk from uncontrolled nanotech",
        "Physics limits on FTL",
        "Dual-use risk of molecular machines",
      ],
      dependencies: [
        "Advanced materials science",
        "Quantum computing maturity",
        "AI-driven design tools",
      ],
      successors: [
        "Post-scarcity manufacturing",
        "Type I civilisation energy systems",
      ],
    },

    {
      id: "med",
      name: "Medicine & Cures",
      color: "#ef4444",
      maturity: 6,
      impact: 10,
      companies: 85,
      projects: 40,
      trl: 6,
      subdomains: [
        "Oncology & Cancer",
        "Neurodegeneration",
        "Infectious Disease",
        "Gene Therapy",
        "Longevity & Aging",
      ],
      currentTech: [
        "mRNA vaccines (Moderna, BioNTech)",
        "CAR-T cell therapy",
        "CRISPR-Cas9 (Casgevy approved)",
        "GLP-1 weight loss drugs",
        "Immunotherapy checkpoints",
      ],
      futureTech: [
        "Universal cancer vaccine (5-10yr)",
        "Alzheimer cure (8-15yr)",
        "Aging reversal / senolytics (15-25yr)",
        "Organ-on-chip drug testing",
      ],
      risks: [
        "Drug resistance evolution",
        "70%+ clinical trial failure rate",
        "Access inequality (low-income nations)",
        "Off-target CRISPR edits",
      ],
      dependencies: [
        "AI drug discovery (AlphaFold)",
        "Biotech manufacturing scale",
        "Regulatory approval pathways (FDA, EMA)",
      ],
      successors: [
        "Personalised genome medicine",
        "Nanobots for drug delivery",
        "Biological age reversal",
      ],
    },

    {
      id: "nrg",
      name: "Energy",
      color: "#f59e0b",
      maturity: 6,
      impact: 9,
      companies: 40,
      projects: 25,
      trl: 6,
      subdomains: [
        "Nuclear Fusion",
        "Solar & Wind",
        "Green Hydrogen",
        "Solid-State Batteries",
        "Smart Grid / Storage",
      ],
      currentTech: [
        "Utility solar (LCOE < $0.02/kWh)",
        "Li-ion grid storage (Fluence, Tesla)",
        "Small modular reactors (NuScale)",
        "Offshore wind (Orsted, Vestas)",
      ],
      futureTech: [
        "Commercial fusion power plant (8-15yr)",
        "Solid-state EV batteries (3-7yr)",
        "Space-based solar power (20-30yr)",
        "Thorium MSR reactors",
      ],
      risks: [
        "Grid instability from intermittent renewables",
        "Critical mineral supply (lithium, cobalt)",
        "Nuclear waste storage",
        "Energy poverty gap (800M without power)",
      ],
      dependencies: [
        "Advanced materials (electrolytes, membranes)",
        "AI grid management",
        "Policy and carbon pricing",
      ],
      successors: [
        "Fusion-powered global grid",
        "Hydrogen economy",
        "Kardashev Type I energy civilisation",
      ],
    },

    {
      id: "mat",
      name: "Advanced Materials",
      color: "#a855f7",
      maturity: 5,
      impact: 8,
      companies: 28,
      projects: 18,
      trl: 5,
      subdomains: [
        "Graphene & 2D Materials",
        "Metamaterials",
        "Perovskites",
        "Biocomposites",
        "Self-Healing Materials",
      ],
      currentTech: [
        "Commercial graphene (First Graphene, Graphenea)",
        "Carbon nanotubes (CNT fibres)",
        "Perovskite solar cells (25%+ efficiency)",
        "Aerogels for insulation",
      ],
      futureTech: [
        "Room-temperature superconductors (10-25yr)",
        "Self-healing polymers at scale (5-10yr)",
        "Programmable smart matter (20-30yr)",
      ],
      risks: [
        "Nano-toxicology unknowns (lung/CNS)",
        "Manufacturing scale-up cost",
        "IP concentration in few labs",
      ],
      dependencies: [
        "Precision manufacturing (atomic layer deposition)",
        "AI materials discovery (GNoME)",
        "Computational modelling",
      ],
      successors: [
        "Molecular manufacturing",
        "Self-assembling nanostructures",
      ],
    },

    {
      id: "neu",
      name: "Neurotech & BCI",
      color: "#6366f1",
      maturity: 4,
      impact: 9,
      companies: 22,
      projects: 14,
      trl: 4,
      subdomains: [
        "Brain-Computer Interfaces",
        "Neural Implants",
        "Cognitive Enhancement",
        "Neural Signal Decoding",
        "Brain-to-Brain Communication",
      ],
      currentTech: [
        "Neuralink N1 (1024 electrodes, paralysis patients)",
        "Synchron Stentrode (blood-vessel BCI)",
        "DBS for Parkinson's & depression",
        "EEG headsets (Emotiv, OpenBCI)",
      ],
      futureTech: [
        "Full-bandwidth wireless BCI (5-10yr)",
        "Memory augmentation implants (10-20yr)",
        "Brain-to-brain communication (20-30yr)",
      ],
      risks: [
        "Privacy of thought / mental surveillance",
        "Hacking neural implants",
        "Enhancement inequality",
        "Long-term glial scar tissue formation",
      ],
      dependencies: [
        "Biocompatible flexible electronics",
        "AI signal decoding (100M neurons)",
        "Wireless power delivery to implants",
      ],
      successors: [
        "Merged human-AI cognition",
        "Neural cloud computing",
        "Post-biological intelligence",
      ],
    },

    {
      id: "spc",
      name: "Space & Robotics",
      color: "#94a3b8",
      maturity: 5,
      impact: 8,
      companies: 35,
      projects: 22,
      trl: 5,
      subdomains: [
        "Heavy Lift Launch",
        "Lunar Infrastructure",
        "Mars Colonisation",
        "Humanoid Robots",
        "Satellite Mega-Constellations",
      ],
      currentTech: [
        "SpaceX Starship (fully reusable)",
        "ISS / commercial stations (Axiom)",
        "Figure 02 & Tesla Optimus humanoids",
        "Starlink 6000+ satellites",
      ],
      futureTech: [
        "Permanent lunar base (5-10yr)",
        "First humans on Mars (5-8yr)",
        "1000+ humanoid robots in factories (3-5yr)",
        "Space mining (10-20yr)",
      ],
      risks: [
        "Kessler syndrome (orbital debris cascade)",
        "Life support failure on Mars",
        "Humanoid safety in human environments",
        "Planetary protection contamination",
      ],
      dependencies: [
        "ISRU (oxygen/water from regolith)",
        "AI autonomy for remote operations",
        "Launch cost < $100/kg to LEO",
      ],
      successors: [
        "Mars colony self-sufficiency",
        "Asteroid mining economy",
        "Solar system civilisation",
      ],
    },

    {
      id: "sec",
      name: "Cybersecurity",
      color: "#f97316",
      maturity: 6,
      impact: 8,
      companies: 30,
      projects: 16,
      trl: 6,
      subdomains: [
        "Post-Quantum Cryptography",
        "Zero-Trust Architecture",
        "AI Security",
        "Biometric Auth",
        "Threat Intelligence AI",
      ],
      currentTech: [
        "CRYSTALS-Kyber PQC (NIST 2024 standard)",
        "SASE zero-trust platforms (Zscaler, Cloudflare)",
        "AI-powered SOC (Crowdstrike Falcon)",
        "Passkeys / FIDO2",
      ],
      futureTech: [
        "Quantum-safe global internet (5-10yr)",
        "Autonomous AI cyber defender (3-7yr)",
        "Behavioural biometrics authentication (3-5yr)",
      ],
      risks: [
        "Nation-state APT attacks (China, Russia, N. Korea)",
        "Harvest-now-decrypt-later quantum threat",
        "AI-generated spear phishing at scale",
        "Software supply chain attacks",
      ],
      dependencies: [
        "Post-quantum standards (NIST, ETSI)",
        "AI capabilities for attack/defence",
        "Hardware security modules",
      ],
      successors: [
        "AI-native security fabric",
        "Zero-knowledge proof-based internet",
        "Quantum communication network",
      ],
    },

    {
      id: "gov",
      name: "Global Governance",
      color: "#14b8a6",
      maturity: 4,
      impact: 7,
      companies: 18,
      projects: 12,
      trl: 4,
      subdomains: [
        "AI Regulation",
        "Digital Identity",
        "Climate Policy",
        "Global Health Systems",
        "Digital Currencies (CBDC)",
      ],
      currentTech: [
        "EU AI Act (2024 — world's first AI law)",
        "WHO Pandemic Treaty negotiations",
        "CBDC pilots (China, EU, Nigeria)",
        "Digital public infrastructure (India Stack)",
      ],
      futureTech: [
        "Global AI governance framework (3-7yr)",
        "Universal digital identity (5-10yr)",
        "AI-assisted policymaking (10-20yr)",
      ],
      risks: [
        "Regulatory fragmentation (US vs EU vs China)",
        "Authoritarian use of digital surveillance",
        "Treaty non-compliance and enforcement gaps",
        "Democratic erosion via AI propaganda",
      ],
      dependencies: [
        "International cooperation (G7, G20, UN)",
        "Technical standards bodies (ISO, IEEE, ITU)",
        "Political will for global coordination",
      ],
      successors: [
        "AI-governed global commons",
        "Planetary coordination systems",
      ],
    },

    {
      id: "bld",
      name: "Smart Construction",
      color: "#d97706",
      maturity: 5,
      impact: 7,
      companies: 20,
      projects: 14,
      trl: 5,
      subdomains: [
        "3D-Printed Buildings",
        "Living / Biological Materials",
        "Smart City OS",
        "Underground Infrastructure",
        "BIM & Digital Twins",
      ],
      currentTech: [
        "ICON Vulcan 3D concrete printing",
        "BIM (Autodesk Revit, Bentley)",
        "AI-driven smart building systems for real-time energy optimization",
        "Prefab modular housing (Katerra model)",
      ],
      futureTech: [
        "Fully 3D-printed cities (10-20yr)",
        "Self-repairing living buildings (10-20yr)",
        "Underground city networks (20-40yr)",
        "AI autonomous construction robots",
      ],
      risks: [
        "Building code lag behind innovation",
        "Material fire and safety certification",
        "Cybersecurity of smart infrastructure",
        "Workforce displacement",
      ],
      dependencies: [
        "Advanced materials (bio-concrete, mycelium)",
        "Autonomous robotics",
        "AI design and structural analysis",
      ],
      successors: [
        "Programmable built environment",
        "Orbital habitat construction",
        "Self-building infrastructure",
      ],
    },

    {
      id: "cos",
      name: "Cosmetics & Bio-Enhancement",
      color: "#ec4899",
      maturity: 5,
      impact: 6,
      companies: 25,
      projects: 16,
      trl: 5,
      subdomains: [
        "Longevity Science",
        "Epigenetic Reprogramming",
        "Gene Therapy Cosmetics",
        "Sensory Enhancement",
        "Biohacking",
      ],
      currentTech: [
        "Senolytics (dasatinib+quercetin in trials)",
        "NAD+ / rapamycin longevity protocols",
        "Retinol / tretinoin science",
        "GLP-1 aesthetic repurposing",
      ],
      futureTech: [
        "Epigenetic age reversal to cellular youth (10-20yr)",
        "Designer sensory enhancement (15-25yr)",
        "Gene-edited appearance (20-30yr)",
      ],
      risks: [
        "Access inequality — only for the wealthy",
        "Unregulated biohacking clinics",
        "Off-target genetic effects",
        "Social pressure to enhance",
      ],
      dependencies: [
        "Gene therapy delivery vectors",
        "AI personalisation of interventions",
        "Biomarker testing and monitoring",
      ],
      successors: [
        "Biological age reversal",
        "Transhumanist body design",
        "Post-biological human form",
      ],
    },

    {
      id: "smt",
      name: "Smart Systems",
      color: "#14b8a6",
      maturity: 6,
      impact: 8,
      companies: 50,
      projects: 22,
      trl: 6,
      subdomains: [
        "Smart City Platforms",
        "Industrial IoT / Industry 4.0",
        "Precision Agriculture",
        "Digital Twins",
        "Autonomous Logistics",
        "V2G Networks",
      ],
      currentTech: [
        "Smart city platforms / Industrial IoT / Precision agriculture / Digital twins",
      ],
      futureTech: [
        "Autonomous logistics / V2G networks / Digital twin cities / Vertical farming at scale",
      ],
      farTech: [
        "SPECULATIVE (20-100yr)",
        "CIVILISATION-SCALE (100-1000+yr)",
        "Autonomous city OS / Global transcontinental smart grid / Satellite IoT layer",

        "SPECULATIVE (20-100yr)",
        "CIVILISATION-SCALE (100-1000+yr)",
        "Autonomous city OS / Global transcontinental smart grid / Satellite IoT layer",
      ],
      risks: [
        "Cybersecurity of critical infrastructure",
        "Digital divide in smart city access",
        "Data privacy from pervasive sensors",
        "Single points of failure in networked cities",
      ],
      dependencies: [
        "5G / 6G connectivity",
        "AI analytics platforms",
        "IoT sensor hardware at scale",
        "Edge computing infrastructure",
      ],
      successors: [
        "Autonomous city OS",
        "Global transcontinental smart grid",
        "Planetary sensor layer",
      ],
    },

    {
      id: "agri",
      name: "AgriTech & Food Systems",
      color: "#22c55e",
      maturity: 6,
      impact: 8,
      companies: 30,
      projects: 18,
      trl: 6,
      subdomains: [
        "Precision Farming",
        "Farm Robotics",
        "Vertical Farming",
        "Alternative Proteins",
        "Smart Aquaculture",
      ],
      currentTech: [
        "Autonomous tractors",
        "Crop-monitoring drones",
        "Livestock biometric monitoring",
        "Precision fermentation",
      ],
      futureTech: [
        "Autonomous farm networks (5-10yr)",
        "Commercial vertical farming scale-out (5-10yr)",
        "Cultivated meat price parity (10-20yr)",
      ],
      risks: [
        "Food supply concentration",
        "Biosecurity in controlled farms",
        "High energy demand for indoor agriculture",
        "Water access inequality",
      ],
      dependencies: [
        "Satellite sensing",
        "AI agronomy models",
        "Robotics at field scale",
        "Cold-chain logistics",
      ],
      successors: [
        "Fully autonomous farms",
        "Planetary food optimisation",
        "Closed-loop bio-industrial agriculture",
      ],
    },

    {
      id: "domain-syn",
      name: "Synthetic Biology",
      color: "#22c55e",
      icon: "⬡",
      currentTech:
        "AI protein design / Ginkgo bio-foundry / Synthetic spider silk / Precision fermentation",
      nearTech:
        "Synthetic genomes / Xenobiology / Living materials / Cell-free systems",
      farTech:
        "De novo life forms / DNA computing / Synthetic ecosystems / Terraforming biology",
      companies: 45,
      maturity: 5,
      impact: 9,
    },
    {
      id: "3dp",
      name: "3D Printing",
      color: "#f97316",
      maturity: 6,
      impact: 8,
      companies: 40,
      projects: 20,
      trl: 6,
      subdomains: [
        "Industrial",
        "Medical Bioprinting",
        "Construction",
        "Metal Additive",
        "Polymer",
        "Food Printing",
        "Micro-fabrication",
      ],
      currentTech: [
        "Powder bed fusion",
        "FDM polymer lines",
        "Bioprinting scaffolds",
        "Construction gantry printers",
      ],
      futureTech: [
        "High-speed multi-material systems",
        "Printed electronics at scale",
        "In-hospital tissue manufacturing",
      ],
      risks: [
        "Unsafe printed pressure parts",
        "Material contamination",
        "Unvalidated medical prints",
        "Weaponisation attempts",
      ],
      dependencies: [
        "Advanced materials",
        "Machine vision QA",
        "Digital twin calibration",
      ],
      successors: [
        "Autonomous print farms",
        "Localized manufacturing grids",
      ],
    },
    {
      id: "robotics",
      name: "Robotics",
      color: "#0ea5e9",
      maturity: 7,
      impact: 9,
      companies: 70,
      projects: 30,
      trl: 7,
      subdomains: [
        "Industrial",
        "Medical",
        "Service",
        "Humanoids",
        "Autonomous Vehicles",
        "Warehouse",
        "Agriculture",
        "Construction",
      ],
      currentTech: [
        "Industrial arms",
        "AMR fleets",
        "Surgical robotics",
        "Warehouse automation",
      ],
      futureTech: [
        "General-purpose humanoids",
        "Dexterous manipulation at scale",
        "Robot-first logistics corridors",
      ],
      risks: [
        "Workforce displacement",
        "Safety incidents",
        "Cyber-physical security",
      ],
      dependencies: ["AI perception", "Battery systems", "Edge compute"],
      successors: [
        "Multi-robot city infrastructure",
        "Robot-native production chains",
      ],
    },
    {
      id: "autojobs",
      name: "Automation Jobs",
      color: "#14b8a6",
      maturity: 7,
      impact: 9,
      companies: 100,
      projects: 40,
      trl: 7,
      subdomains: [
        "Construction",
        "Healthcare",
        "Retail",
        "Logistics",
        "Manufacturing",
        "Agriculture",
        "Mining",
        "Energy",
        "Hospitality",
        "Finance",
        "Transportation",
        "Education",
        "Government",
        "IT/Cyber",
        "Media",
      ],
      currentTech: [
        "RPA",
        "Industrial automation",
        "Vision QA",
        "Workflow orchestration",
      ],
      futureTech: [
        "Fully autonomous back-office loops",
        "Cross-industry autonomous operations",
      ],
      risks: [
        "Governance gaps",
        "Bias in automation decisions",
        "Operational over-dependence",
      ],
      dependencies: [
        "Process mapping",
        "Reliable telemetry",
        "Human-in-the-loop controls",
      ],
      successors: ["Autonomous enterprise operating systems"],
    },
  ],
};
